//
//  DeviceDBModel.swift
//  
//
//  Created by Kanstantsin Bucha on 07/01/2023.
//

import Foundation
import Fluent
import Vapor

//public final class DeviceDBModel: Model, CustomStringConvertible {
//    // Name of the table or collection.
//    public static let schema = "devices"
//
//    // MARK: - Autogenerated On Save
//    
//    @ID(key: .id)
//    public var id: UUID?
//    
//    //
//    
//    @Field(key: "User")
//    public var user: UUID
//}
