//
//  DeviceReport.swift
//  
//
//  Created by Kanstantsin Bucha on 09/08/2022.
//

import Foundation
import Fluent
import Vapor

fileprivate enum DeviceReportDBKeys: String {
    case millis
    case busVoltage
    case coZeroV
    case coV
    case coPpm
    case tempCelsius
    case pressureHPa
    case humidity
    case gasResistance
    case iaq
    case staticIaq
    case co2Equivalent
    case breathVocEquivalent
    case compGasValue
    case gasPercentage
    case deviceID
    case createdAt
    
    var key: FieldKey {
        return .string(self.rawValue)
    }
}

// {"coZeroV":0.392248,"coV":0.393188,"coPpm":0.234865,"tempCelsius":28.61,"pressureHPa":1005.05,"humidity":41.653,"gasResistance":739592,"iaq":86.50568,"staticIaq":51.86747,"co2Equivalent":607.4699,"breathVocEquivalent":0.750507,"compGasValue":0,"gasPercentage":0},"createdAt":1640236388,"_id":"0MLwpEtAKkTSU54f"}]}

public final class DeviceReportDBModel: Model, CustomStringConvertible {
    // Name of the table or collection.
    public static let schema = "device_reports"

    // MARK: - Autogenerated On Save
    
    @ID(key: .id)
    public var id: UUID?
    
    @Field(key: DeviceReportDBKeys.createdAt.key)
    public var createdAt: Date?
    
    // MARK: - Data Fields
    
    @Field(key: DeviceReportDBKeys.deviceID.key)
    public var deviceID: String?

    @Field(key: DeviceReportDBKeys.millis.key)
    public var millis: UInt32?
    
    @Field(key: DeviceReportDBKeys.busVoltage.key)
    public var busVoltage: Float?
    
    @Field(key: DeviceReportDBKeys.coZeroV.key)
    public var coZeroV: Float?
    
    @Field(key: DeviceReportDBKeys.coV.key)
    public var coV: Float?
    
    @Field(key: DeviceReportDBKeys.coPpm.key)
    public var coPpm: Float?
    
    @Field(key: DeviceReportDBKeys.tempCelsius.key)
    public var tempCelsius: Float?
    
    @Field(key: DeviceReportDBKeys.pressureHPa.key)
    public var pressureHPa: Float?
    
    @Field(key: DeviceReportDBKeys.humidity.key)
    public var humidity: Float?
    
    @Field(key: DeviceReportDBKeys.gasResistance.key)
    public var gasResistance: Float?
    
    @Field(key: DeviceReportDBKeys.iaq.key)
    public var iaq: Float?
    
    @Field(key: DeviceReportDBKeys.staticIaq.key)
    public var staticIaq: Float?
    
    @Field(key: DeviceReportDBKeys.co2Equivalent.key)
    public var co2Equivalent: Float?
    
    @Field(key: DeviceReportDBKeys.breathVocEquivalent.key)
    public var breathVocEquivalent: Float?
    
    @Field(key: DeviceReportDBKeys.compGasValue.key)
    public var compGasValue: Float?
    
    @Field(key: DeviceReportDBKeys.coZeroV.key)
    public var gasPercentage: Float?
    
    public var description: String {
        return """
            <DeviceReportDBModel id: \(String(describing: id)), deviceID: \(String(describing: deviceID)), \
            createdAt: \(String(describing: createdAt)), temp: \(String(describing: tempCelsius)), \
            iaq: \(String(describing: createdAt)), coPpm: \(String(describing: coPpm)) >
            """
    }
    
    public init() {}

    public init(_ model: DeviceReportAPIModel) throws {
        id = model.id ?? UUID()
        createdAt = Date()
        deviceID = model.deviceId
        let data = model.data
        millis = data?.millis
        busVoltage = data?.busVoltage
        coZeroV = data?.coZeroV
        coV = data?.coV
        coPpm = data?.coPpm
        tempCelsius = data?.tempCelsius
        pressureHPa = data?.pressureHPa
        humidity = data?.humidity
        gasResistance = data?.gasResistance
        iaq = data?.iaq
        staticIaq = data?.staticIaq
        co2Equivalent = data?.co2Equivalent
        breathVocEquivalent = data?.breathVocEquivalent
        compGasValue = data?.compGasValue
        gasPercentage = data?.gasPercentage
    }
}

struct CreateDeviceReportsTableMigration: AsyncMigration {
    func prepare(on database: Database) async throws {
        print("prepare CreateDeviceReportsTableMigration started")
        try await database.schema(DeviceReportDBModel.schema)
            .id()
            .field(DeviceReportDBKeys.deviceID.key, .string)
            .field(DeviceReportDBKeys.createdAt.key, .datetime)
            .field(DeviceReportDBKeys.millis.key, .uint32)
            .field(DeviceReportDBKeys.busVoltage.key, .float)
            .field(DeviceReportDBKeys.coZeroV.key, .float)
            .field(DeviceReportDBKeys.coV.key, .float)
            .field(DeviceReportDBKeys.coPpm.key, .float)
            .field(DeviceReportDBKeys.tempCelsius.key, .float)
            .field(DeviceReportDBKeys.pressureHPa.key, .float)
            .field(DeviceReportDBKeys.humidity.key, .float)
            .field(DeviceReportDBKeys.gasResistance.key, .float)
            .field(DeviceReportDBKeys.iaq.key, .float)
            .field(DeviceReportDBKeys.staticIaq.key, .float)
            .field(DeviceReportDBKeys.co2Equivalent.key, .float)
            .field(DeviceReportDBKeys.breathVocEquivalent.key, .float)
            .field(DeviceReportDBKeys.compGasValue.key, .float)
            .field(DeviceReportDBKeys.gasPercentage.key, .float)
            .create()
        
        print("prepare CreateDeviceReportsTableMigration finished")
    }
    
    func revert(on database: Database) async throws {
        print("revert CreateDeviceReportsTableMigration")
    }
}
