name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker login -u {{ var.DOCKER_USER }} -p {{ secrets.DOCKER_PASSWORD }}
        docker compose -f docker-compose.yml -f docker-production.yml build
        docker compose -f docker-compose.yml -f docker-production.yml push
